In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from scipy import sparse
from sys import getsizeof
import numpy as np
import os
import datetime as dt
import meteomatics.api as metapi
import json

from __future__ import print_function

directory = r"D:\Users\xubil\OneDrive\Documents\Wildfires Data NPZ"
data = {}
processed = {}
coords = json.load(open('Extract/coords.json'))

# Get xgboost model

In [19]:
username = 'student_xu_bill' #'python-community' #'student_xu_bill'
password = '7o7zT54NlW' #'Umivipawe179' #'7o7zT54NlW'

In [4]:
xmin, xmax, ymin, ymax = (coords["4326"]["xmin"]), (coords["4326"]["xmax"]), (coords["4326"]["ymin"]), (coords["4326"]["ymax"])

In [5]:
xmin, xmax, ymin, ymax

(-80.42823, -60.64253, 44.60349, 52.55283)

In [7]:
lat_N = xmax
lon_W = ymin
lat_S = xmin
lon_E = ymax
res_lat = (xmax-xmin)/597
res_lon = (ymax-ymin)/364

In [15]:
parameter_grid = ['t_max_2m_24h:C', 't_min_2m_24h:C', 'precip_24h:mm', 'absolute_humidity_2m:gm3', 'soil_moisture_index_-5cm:idx']
# Choose from https://www.meteomatics.com/en/api/available-parameters/

In [20]:
done = False

for year in range (2013, 2023):
    startdate_grid = dt.datetime(year, 1, 1)
    end = dt.datetime(year, 12, 31)

    while startdate_grid <= end:
        print(startdate_grid)

        savelist = []

        for param in parameter_grid:
            try:
                df_grid = metapi.query_grid(startdate_grid, param, lat_N, lon_W, lat_S, lon_E, res_lat, res_lon, username, password)
                savelist.append(df_grid)
            except Exception as e:
                print("Failed, the exception is {}".format(e))
                done = True
                break
        
        np.save("D:/Users/xubil/OneDrive/Documents/Wildfires Data NPZ/weather/"+year+"/"+startdate_grid.strftime("%m/%d/%Y"), savelist)

        del savelist

        if (done):
            break
    if (done):
        break

2013-01-01 00:00:00
Failed, the exception is Request with valid date 2013-01-01T00:00:00Z requires data access before 2023-11-29T00:00:00Z, which is not granted with this subscription type (e.g. trial). The valid time period for this account type starts at 2023-11-29T00:00:00Z and ends at 2025-11-30T00:00:00Z. Please contact sales@meteomatics.com and we are happy to provide an extended trial or an upgrade of your account.

TypeError: can only concatenate str (not "int") to str

In [13]:
startdate_grid = dt.datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)

In [14]:
print("grid:")
try:
    df_grid = metapi.query_grid(startdate_grid, parameter_grid, lat_N, lon_W, lat_S, lon_E, res_lat, res_lon,
                             username, password)
    print (df_grid.head())
except Exception as e:
    print("Failed, the exception is {}".format(e))

grid:
Failed, the exception is Query contains a whitespace

In [11]:
df_grid

lon,44.603490,44.625329,44.647168,44.669007,44.690845,44.712684,44.734523,44.756362,44.778201,44.800040,...,52.356280,52.378119,52.399958,52.421797,52.443636,52.465475,52.487313,52.509152,52.530991,52.552830
lat,,,,,,,,,,,,,,,,,,,,,
-60.642530,-1.1,-1.1,-1.1,-1.1,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,...,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2
-60.675672,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,...,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2
-60.708814,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,...,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2
-60.741956,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,...,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2
-60.775098,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,...,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2,-1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
-80.295662,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,...,-32.0,-31.9,-31.9,-31.9,-31.9,-31.9,-31.9,-31.9,-31.9,-31.8
-80.328804,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,...,-32.1,-32.0,-32.0,-32.0,-32.0,-32.0,-32.0,-32.0,-32.0,-31.9
-80.361946,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,...,-32.1,-32.1,-32.1,-32.1,-32.1,-32.1,-32.1,-32.1,-32.1,-32.0
-80.395088,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,-35.1,...,-32.2,-32.2,-32.2,-32.2,-32.2,-32.2,-32.2,-32.2,-32.2,-32.1
-80.428230,-35.0,-35.0,-35.0,-35.0,-35.0,-35.0,-35.0,-35.0,-35.0,-35.0,...,-32.3,-32.3,-32.3,-32.3,-32.3,-32.3,-32.2,-32.2,-32.2,-32.2

In [49]:
df_grid

lon,44.000000,44.021978,44.043956,44.065934,44.087912,44.109890,44.131868,44.153846,44.175824,44.197802,...,51.802198,51.824176,51.846154,51.868132,51.890110,51.912088,51.934066,51.956044,51.978022,52.000000
lat,,,,,,,,,,,,,,,,,,,,,
-60.000000,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.0,-2.0,...,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4
-60.033501,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.0,-2.0,...,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4
-60.067002,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.0,-2.0,...,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4
-60.100503,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.0,...,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4
-60.134003,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,-2.1,...,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4,-2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
-79.865997,-42.8,-42.8,-42.7,-42.7,-42.7,-42.7,-42.7,-42.7,-42.7,-42.7,...,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7
-79.899497,-42.7,-42.7,-42.7,-42.7,-42.7,-42.7,-42.7,-42.7,-42.6,-42.6,...,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7
-79.932998,-42.7,-42.6,-42.6,-42.6,-42.6,-42.6,-42.6,-42.6,-42.6,-42.6,...,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7
-79.966499,-42.6,-42.6,-42.6,-42.6,-42.6,-42.6,-42.6,-42.6,-42.5,-42.5,...,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7
-80.000000,-42.6,-42.5,-42.5,-42.5,-42.5,-42.5,-42.5,-42.5,-42.5,-42.5,...,-40.8,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7,-40.7

In [2]:
def change_zoom(x_min, x_max, y_min, y_max):
    ratio_y, ratio_x = (y_max-y_min)/36400, (x_max-x_min)/59700
    

    for subdir in data:
        processed[subdir] = {}

        for filename in data[subdir]:

            data_process = data[subdir][filename][y_min:y_max, x_min:x_max] # To csc speeds up processing

            N, M = data_process.shape
            s, t = int(400*ratio_y), int(400*ratio_x)          # decimation factors for y and x directions
            T = sparse.csc_matrix((np.ones((M,)), np.arange(M), np.r_[np.arange(0, M, t), M]), (M, (M-1) // t + 1))
            S = sparse.csr_matrix((np.ones((N,)), np.arange(N), np.r_[np.arange(0, N, s), N]), ((N-1) // s + 1, N))
            result = S @ data_process @ T     # downsample by binning into s x t rectangles
            processed[subdir][filename] = result.todense() 
    
    return processed

In [5]:
for filename in os.listdir(directory):
    print("Reading from ",filename)
    filedir = os.path.join(directory, filename)
    if (filename == "fires" or filename == "Ignore"):
        continue

    data[filename] = {}

    for npzname in os.listdir(filedir):
        # print(npzname)
        finaldir = os.path.join(filedir, npzname)
        data[filename][npzname] = sparse.load_npz(finaldir).tocsc()

Reading from  aq_routes_2020_l_arc_f
Reading from  bdat_hypso_l_arc
Reading from  canards_sauv_mhb_2008_s_poly
Reading from  canards_sauv_mhnb_2008_s_poly
Reading from  data-npz_bdtq_hydro_s_poly
Reading from  dmti_transmissionlines_2021_l_arc
Reading from  fires
Reading from  Ignore
Reading from  mrnf_20k_peu_ecofo_ori_poly_f